name: "sugar-refine"
tag: "${data.height}_${rmspace:${basename:${data.mesh_name}},_}"
exp_root_dir: "outputs"
seed: 61

data_type: "single-image-gs-datamodule"
data: # threestudio/data/image.py -> SingleImageDataModuleConfig
  mesh_name: ???
  train_data_path : input/${data.mesh_name}/train
  val_data_path: input/${data.mesh_name}/val
  test_data_path: input/${data.mesh_name}/test
  height: 256
  width: 256
  # resolution_milestones: [200, 300]
  default_elevation_deg: 5.0
  default_azimuth_deg: 0.0
  default_camera_distance: 3.8
  default_fovy_deg: 20.0
  batch_size: 1
  requires_depth: ${cmaxgt0orcmaxgt0:${system.loss.lambda_depth},${system.loss.lambda_depth_rel}}
  requires_normal: ${cmaxgt0:${system.loss.lambda_normal}}


system_type: "sugar-static-system"
system:
  stage: sugar
  postprocess: false

  geometry_type: "sugar"
  geometry:
    position_lr: 0.00016 # [0, 0.00048, 0.0000016, 3000] # 0.0025, 0.05
    scaling_lr: 0.005
    feature_lr: 0.005
    opacity_lr: 0.05
    rotation_lr: 0.001

    spatial_extent: ${data.default_camera_distance}
    spatial_lr_scale: 1

    n_gaussians_per_surface_triangle: 6
    learnable_positions: true
    surface_mesh_to_bind_path: input/meshes/${data.mesh_name}/${data.mesh_name}.obj

    init_gs_opacity: 0.9

    init_gs_scales_s: 1.3

  renderer_type: "diff-sugar-rasterizer-normal"
  renderer:
    debug: false
    invert_bg_prob: 1.0
    back_ground_color: [0.0, 0.0, 0.0]

  material_type: "no-material" # unused
  material:
    n_output_dims: 0

  background_type: "solid-color-background" # unused

  freq:
    ref_only_steps: 0
    guidance_eval: 0
    input_normal: 10000
    start_sugar_reg: 3000
    reset_neighbors: 50

  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    # lambda_sds: 0.01
    lambda_rgb: 5000. # 5000
    lambda_mask: 500. # 500.
    lambda_ssim: 100.
    lambda_depth: 0. # 0.05
    lambda_depth_rel: 0. # [0, 0, 0.05, 100]
    lambda_normal: 0. # [0, 0, 0.05, 100]
    lambda_normal_smooth: 0.
    lambda_normal_depth_consistency: 0.

    lambda_normal_consistency: 10.
    lambda_laplacian_smoothing: 1.

    # For sugar
    lambda_opacity_max: 0.
    lambda_opacity_binary: 1.
    lambda_sugar_density_reg: 1.
    lambda_sugar_sdf_normal_reg: 1.

    # tv reg
    lambda_rgb_tv: 1.0
    lambda_normal_tv: 1.0
    lambda_depth_tv: 1.0

  optimizer:
    name: Adam
    args:
      lr: 0.01
      betas: [0.9, 0.99]
      eps: 1.e-8
    params:
      background:
        lr: 0.001

trainer:
  max_steps: 4000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 1000
  enable_progress_bar: true
  precision: 32

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
